version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nextmile_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - nextmile_network

  mongo-express:
    image: mongo-express:latest
    container_name: nextmile_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - nextmile_network

  chatbot:
    build: ./chatbot
    container_name: nextmile_chatbot
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/nextmile_chatbot?authSource=admin
    depends_on:
      - mongodb
    networks:
      - nextmile_network

  frontend:
    build: ./Frontend
    container_name: nextmile_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - chatbot
    networks:
      - nextmile_network

volumes:
  mongodb_data:

networks:
  nextmile_network:
    driver: bridge